Map cell value on uri
MaastrichtU-CDS/EPND-FAIRification pull request #33
Opened 2022-09-19 08:42 UTC by shashankmc

Resolved the issue on #28 . Needs validation @matthijssloep

2022-11-04 14:47 UTC, aiaragomes commented
APOE is not appearing in the publish preview for me.

2022-11-11 10:11 UTC, aiaragomes requested changes
There is still a problem with APOE, see comments.

2022-11-14 09:15 UTC, shashankmc commented on management_webpage/flaskr/getCategories.py
> +    print(f"This query is being used  for obtaing \
Sorted

2022-11-14 09:17 UTC, shashankmc commented on management_webpage/flaskr/mapDatasets.py
> +                useLinkdata.createCellLink(selectedValue['categoryUri'].loc[0], cdmValue, catValue)
Resolved with new commit. New issue with "UNKNOWN" selection - if previous value was something meaningful and the selection is modified to "UNKNOWN", nothing happens. Need to bake in that condition.

2022-11-14 12:23 UTC, shashankmc commented
@aiaragomes Should properly work now for unknown selection during cell mapping.

2022-11-14 12:27 UTC, shashankmc commented
> APOE is not appearing in the publish preview for me.

@aiaragomes The header doesn't display "APOE" during preview but displays "ncbi:gene/348" is which the URI for APOE. Does that make sense?

2022-11-29 15:43 UTC, merged